### ISSUE TITLE
require_grad or requires_grad

### ISSUE THREAD

**Issue by travishsu** [zh217/torch-dct#10]
Hi, thanks for this great Pytorch version of DCT, it helps me and our team a lot.

I'm not quite familiar with autograd mechanism and not sure what the difference between require_grad and requires_grad is, are they the same thing but different variable name in different pytorch version? or is it a typo?

https://github.com/zh217/torch-dct/blob/b6823eadec0fb35122e34cea22cb6cbe3c563d9b/torch_dct/_dct.py#L202

**Comment by zh217** [comment]
Hi, you are right, that it is a typo. Sorry about it. Would you care to make a pull request for it?

**Comment by travishsu** [comment]
It's ok, leaving this to you.
