### ISSUE TITLE
torch. rfft is not the right implementation of DCT

### ISSUE THREAD

**Issue by TianhaoFu** [zh217/torch-dct#22]
Hi,

I read the docs of torch. rfft. It says that torch. rfft is implementation of FFT.  But FFT is not dct. In your code you use torch. rfft to implement dct.  Do you think your code is right?

Thanks.

**Comment by iamjanvijay** [comment]
Hi @TianhaoFu! 
Please have a look at this comment: https://github.com/zh217/torch-dct/issues/15#issuecomment-851439294
I have verified this and it works well for torch==1.10.
Thanks.

**Comment by jonnor** [comment]
This can be closed now. Fixed in PR #24
