### ISSUE TITLE
What is the difference between DCT-I and DCT-II?

### ISSUE THREAD

**Issue by mo666666** [zh217/torch-dct#27]
I am a new learner of discrete cosine transform. Can you tell me what is the difference between DCT-I and DCT-II?

**Comment by zh217** [comment]
Please refer to https://en.wikipedia.org/wiki/Discrete_cosine_transform, especially the insert in the section titled "Informal overview".

**Comment by mo666666** [comment]
Thank you for your reply. I will refer to the reference.
