### ISSUE TITLE
Incompatible with torch.compile

### ISSUE THREAD

**Issue by bishshoy** [zh217/torch-dct#28]
The current module is incompatible in my projects with `torch.compile`. I was able to resolve the error by changing the `np.pi` calls to `torch.tensor(math.pi)` and convert all `numpy` operations to `torch` operations.

**Comment by zh217** [comment]
I don't personally use `torch.compile` module. If you already have a version that suits your needs, would you like to open a pull request for it?

**Comment by bishshoy** [comment]
Will do.

**Comment by bishshoy** [comment]
I couldn't get the tests to fail even with `torch.compile`. Could've been an issue at my end. I will need to investigate more. For now, the issue could be closed.
