### ISSUE TITLE
 dct.dct parameters

### ISSUE THREAD

**Issue by doublejtoh** [zh217/torch-dct#5]
in https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.fftpack.dct.html, it has parameter "n" which is described as optional Length of the transform. I want to use this parameter but this package's dct function seems to have no such parameter. Is there any possible way to use this parameter or should it be reimplemented?

**Comment by zh217** [comment]
Unfortunately this is not easy to do, since the function we depended on, torch.rfft and torch.irfft, exposes no such parameter. I guess you'd have to do some padding yourself for the moment being.
