### ISSUE TITLE
not equal with scipy.fftpack.dct

### ISSUE THREAD

**Issue by machengcheng2016** [zh217/torch-dct#6]
The function dct is not equal with scipy.fftpack.dct. 
I assume that scipy.fftpack.dct is correct, since scipy.fftpack.dct is equal with matlab's dct.

**Comment by machengcheng2016** [comment]
No matter norm is 'ortho' or not, the output of dct is just different with scipy.fftpack.dct and matlab's dct

**Comment by mmmmayi** [comment]
> The function dct is not equal with scipy.fftpack.dct.
> I assume that scipy.fftpack.dct is correct, since scipy.fftpack.dct is equal with matlab's dct.

So do you find any function to implement scipy.fftpack.dct in python or in pytorch?

**Comment by machengcheng2016** [comment]
> > The function dct is not equal with scipy.fftpack.dct.
> > I assume that scipy.fftpack.dct is correct, since scipy.fftpack.dct is equal with matlab's dct.
> 
> So do you find any function to implement scipy.fftpack.dct in python or in pytorch?

Sorry for the late. 
Seems it's been a long time that I found this bug... I installed the 'torch-dct' and tried to reproduce this bug just now (Env: python==3.7, scipy==1.3.1). I got four awkward conclusions as follows:

1. The 1D-DCT result of torch_dct is same with that of scipy.fftpack.dct, as long as the _norm_ option is samely set.
Specifically, the result of `torch_dct.dct(torch.from_numpy(numpy_1d_array).float(), norm='ortho')` and that of `scipy.fftpack.dct(numpy_1d_array, norm='ortho')` are the same.
The result of `torch_dct.dct(torch.from_numpy(numpy_1d_array).float())` and that of `scipy.fftpack.dct(numpy_1d_array)` are the same, too.

2. The 2D-DCT result of torch_dct is same with that of scipy.fftpack.dct, as long as the _norm_ option is samely set.
The way of computing 2D-DCT with scipy.fftpack.dct is like `scipy.fftpack.dct(scipy.fftpack.dct(gray_image_numpy.T).T)`, as suggested in https://stackoverflow.com/a/15981676

3) The 1D-DCT result of scipy.fftpack.dct and that of Matlab2018A are different, unless I change the _norm_ option from the default _None_ to  _ortho_.
For example, in Python
`scipy.fftpack.dct(np.array([1., 1., 1.])) = array([6., 0., 0.])
scipy.fftpack.dct(np.array([1., 1., 1.]), norm='ortho') = array([1.73205081, 0., 0.])
torch_dct.dct(torch.FloatTensor([1., 1., 1.])) = tensor([6., 0., 0.])
torch_dct.dct(torch.FloatTensor([1., 1., 1.]), norm='ortho') = tensor([1.7321, 0.0000, 0.0000])
`
in Matlab2018A
`dct([1,1,1])=[1.7321, 0, 0];`

4) The 2D-DCT result of scipy.fftpack.dct and that of Matlab2018A are different, unless I change the _norm_ option from the default _None_ to  _ortho_.

So, I think there are no bugs in torch_dct. Maybe we should check whether the _norm_ option is correctly set.

**Comment by yx-chan131** [comment]
@machengcheng2016 Hi, for point number 2 2D-DCT, could you share the complete code of how you computing DCT in PyTorch and Scipy? I set the norm as "ortho" but the results are not the same.
